version: '3'
services:
  backend:
    image: dan1993/oitube-api
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oitube
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
